<?php
$attributeSetList = $block->listAttributeSet();
?>
<style>
    .fieldset {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 25px 30px;
        padding-right: 0;
    }

    .fieldset h2 {
        margin-bottom: 5px;
        margin-top: 10px;
    }

    .flexContainer {
        display: flex;
        flex-wrap: wrap;
    }

    .flexContainer .field {
        width: 50%;
        padding: 10px 0;
        padding-right: 25px;
    }

    .flexContainer .field input, .flexContainer .field select {
        width: 100%;
        height: 35px;
        margin-top: 7px;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding-left: 15px;
    }

    .fr {
        float: left;
        width: 100%;
    }
</style>
<form class="form" action="<?= $block->getImportUrl() ?>" data-bind="scope: 'address-scope'"
      id="edit_form" method="post" autocomplete="on"
      data-bind="mageInit: {'validation': {}}" data-mage-init='{"validation": {}}' enctype="multipart/form-data">
    <?php echo $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset">
        <div class="flexContainer">
            <div class="entity_att_section fr">
                <div class="attribute_set_list">
                    <div class="field">
                        <label for="attribute_set_id" class="label">
                            <span><?php echo __('CSV Sample') ?></span>
                        </label>
                        <div class="control">
                            <a id="attribute_importer_note" title="Download Sample File"
                               href="<?php echo $block->getDownloadSampleUrl(); ?>">Download sample csv format</a>
                        </div>
                    </div>
                    <?php if ($attributeSetList) { ?>
                        <div class="field required">
                            <label for="attribute_set_id" class="label">
                                <span><?php echo __('Attribute Sets') ?></span>
                            </label>
                            <div class="control">
                                <select
                                    name="attributeset_exitstid" id="attributeset_exitstid"
                                    data-bind="mageInit: {'validation': {required: true}},
                                optionsText: 'label',
                                optionsValue: 'value',
                                optionsCaption: 'Please select Attribute Set'"
                                    title="Entity Type" data-validate="{'validate-select': true}">
                                    <option selected="selected" value="">--Please select--</option>
                                    <?php foreach ($attributeSetList->getItems() as $list) { ?>
                                        <option value="<?php echo $list->getAttributeSetId(); ?>">
                                            <?php echo __($list->getAttributeSetName()); ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="field required">
                        <label for="attribute_set_id" class="label">
                            <span><?php echo __('Select File to Import') ?></span>
                        </label>
                        <div class="control">
                            <input id="attribute_import_file" name="attribute_import_file"
                                   value="" title="Select File to Import"
                                   class="input-file required-entry _required" type="file" aria-required="true">
                        </div>
                    </div>
                </div>

                <div class="field">
                    <div class="primary">
                        <button type="submit" class="action submit primary btn_put_json"><span>Import</span></button>
                    </div>
                </div>

            </div>

        </div>
    </fieldset>
</form>


<script>
    require(['jquery', 'jquery/ui'], function ($) {

        $(".btn_put_json").on("click", function (e) {
            var disable = $(this).attr('disable');
            if (disable != 'disable') {
                var submit = $('#attribute-export-form').submit();
            }
            var error = $('#attribute-export-form').find('.mage-error').length,
                noeError = true;

            if (error > 0) {

                $('.mage-error').each(function () {
                    var styleData = $(this).css('display');
                    if (styleData != 'none') {
                        noeError = false;
                        return false;
                    }
                });
            }
            if (noeError) {
                $(this).attr('disable', 'disable');
            }
            //
        });

    });
</script>
